# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbc5edad8a653037690f4d425396b178c90b8c0502055c318a3e2d6b66e234b841d1181074c43f0afa059ea9de07e4561f7ec9f29d2051fd8cb87554cc197203

test:
  secret_key_base: c50edcb33cb2c7f52a7b26104d716454e12f1b0094d2c39d626624f487c98d323905f071336912e716178521652173ba4c81591126bcc23086eb49fe2a2a8226

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
